apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: ecom-web:v1
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: mariadb-service
            - name: DB_NAME
              value: ecomdb
            - name: DB_USER
              value: ecomuser
            - name: DB_PASS
              value: ecompassword
