name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build and push image
        run: |
          az acr login --name myresumeregistry
          docker build -f docker/Dockerfile.web -t myresumeregistry.azurecr.io/ecom-web:${{ github.sha }} .
          docker push myresumeregistry.azurecr.io/ecom-web:${{ github.sha }}
      - name: Update deployment image
        run: |
          kubectl set image deployment/web-deployment web=myresumeregistry.azurecr.io/ecom-web:${{ github.sha }} --namespace resume-challenge
